spring:
  application:
    name: Spring_data_JPA_homework
  datasource:
    url: jdbc:postgresql://sonarqube-202511104738-db-1:5432/spring_data_jpa_db
    username: postgres
    password: 092367169
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
server:
  port: 8181
